//! examples/proxy_codegen/src/main.zig
//!
//! Uses the zbus_proxies module generated by ProxyScanner to query
//! NetworkManager for the active Wi-Fi connection and UPower for battery level.

const std = @import("std");
const zbus = @import("zbus");
const proxies = @import("zbus_proxies");
const Io = std.Io;

const String = zbus.types.String;

pub fn main() !void {
    var gpa_state = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa_state.deinit();
    const gpa = gpa_state.allocator();

    var threaded = try Io.Threaded.init(gpa, .{});
    defer threaded.deinit();
    const io = threaded.io();

    const conn = try zbus.connect(gpa, io, .System);
    defer conn.deinit();

    var loop = try Io.concurrent(io, zbus.types.Connection.run, .{conn});
    defer _ = loop.cancel(io);

    try conn.hello();

    // ── UPower: list devices ─────────────────────────────────────────────────

    // The generated UPower proxy wraps org.freedesktop.UPower.
    // GetManagedObjects gives us all UPower objects in one call.
    {
        const p = try zbus.proxies.ObjectManager.GetManagedObjects(
            conn,
            null,
            "org.freedesktop.UPower",
            "/org/freedesktop/UPower",
        );
        defer if (p.release() == 1) p.destroy();

        const managed, const arena = p.wait(null) catch |err| {
            std.log.warn("UPower ObjectManager error: {s}", .{@errorName(err)});
            return;
        };
        defer {
            arena.deinit();
            arena.child_allocator.destroy(arena);
        }

        const objs = try managed;
        var it = objs.iterator();
        while (it.next()) |kv| {
            std.log.info("UPower object: {s}", .{kv.key_ptr.value});
        }
    }

    // ── NetworkManager: active connections ───────────────────────────────────

    // Use the generated NMDevice proxy via the proxies module.
    // proxies.NetworkManager is the struct generated from the XML.
    var nm_proxy: proxies.NetworkManager = .{};
    try nm_proxy.bind(
        gpa,
        conn,
        "org.freedesktop.NetworkManager",
        "/org/freedesktop/NetworkManager",
        // No signal handlers for this demo
        zbus.types.SignalManager(proxies.NetworkManager.Signals).Listener{
            .userdata = null,
        },
    );

    // Fetch ActiveConnections property (already populated by bind())
    nm_proxy.properties._mutex.lock();
    const active = nm_proxy.properties.ActiveConnections;
    nm_proxy.properties._mutex.unlock();
    std.log.info("{} active NM connections", .{active.len});
    for (active) |path| std.log.info("  {s}", .{path.value});
}
