/// Interface that represents remote object's DBus interface (aka object proxy) or local publishable DBus interface
const Interface = @This();

name: []const u8,
description: []const u8,

connection: ?*Connection,
object_path: ?[]const u8,

vtable: *const VTable,
refcounter: atomic.Value(isize) = .init(1),

pub const Error = error{
    HandlingFailed,
};

pub const VTable = struct {
    /// Implementation of method_call handler. i is a pointer to *Interface, that is reference to implementation interface field,
    /// so implementation may use @fieldParentPtr to get pointer to implementation itself.
    /// allocator is allocator that was used during Message allocation. Usually backed by ArenaAllocator.
    /// Must return Message (actual response to method_call), null (if no response will be sent), or error (if caller must handle error outside of implementation's scope)
    method_call: *const fn (i: *Interface, message: *Message, allocator: mem.Allocator) Error!?Message,
    /// Pretty much same as with .method_call, but implementation must fully handle org.freedesktop.DBus.Properties interface methods.
    /// Also, Message's .reader() is already populated and advanced past the "interface: `s`" element of body.
    property_op: *const fn (i: *Interface, io: std.Io, message: *Message, allocator: mem.Allocator) Error!?Message,

    /// Implementation-defined destructor. allocator must be a same allocator that was used during .create call
    destroy: *const fn (i: *Interface, allocator: mem.Allocator) void,
};

/// Generate glue from type T. desc is dbus-introspection xml either provided by user or, if null, autogenerated in comptime
pub fn AutoInterface(comptime T: type, comptime desc: ?*const []const u8) type {
    if (!comptime @hasDecl(T, "interface_name"))
        @compileError(
            "Unable to create Interface from " ++ @typeName(T) ++ ": interface prototype missing interface_name declaration",
        );
    if (@TypeOf(T.interface_name) != []const u8)
        @compileError(
            "Unable to create Interface from " ++ @typeName(T) ++ ": interface_name is not of type []const u8 (got " ++ @typeName(@TypeOf(T.interface_name)) ++ " instead)",
        );

    const name = @field(T, "interface_name");
    const description = desc orelse types.introspect(T);

    const methods = methodList(T);
    const properties = propertyList(T);
    const signals = signalList(T);

    const Properties, const TypeUnion, const TypeEnum = PropertyStorage(T);

    var enum_field_names: [signals.len][]const u8 = undefined;
    var enum_field_values: [signals.len]u32 = undefined;
    inline for (signals, 0..) |signal_name, i| {
        enum_field_names[i] = signal_name;
        enum_field_values[i] = i;
    }

    const SignalNamesT = @Enum(
        u32,
        .exhaustive,
        &enum_field_names,
        &enum_field_values,
    );

    const Impl = struct {
        const Template = T;
        pub const PropertiesType = Properties;
        pub const PropertiesUnion = TypeUnion;
        pub const PropertiesEnum = TypeEnum;
        pub const SignalNames = SignalNamesT;

        pub const interface_name = name;

        data: Template = .{},
        properties: Properties = undefined,
        interface: Interface = .{
            .name = name,
            .description = description,
            .connection = null,
            .object_path = null,
            .vtable = &.{
                .method_call = method_call,
                .property_op = property_op,

                .destroy = destroy,
            },
        },

        /// Emit signal that is declared in Template. For all possible signals look at Impl.SignalNames enum.
        /// Value's **resulting*+ signature **must** match resulting signature of type passed into Template Signal's associated declaration.
        pub fn emitSignal(impl: *@This(), signal_name: SignalNames, value: anyopaque, gpa: std.mem.Allocator) !void {
            const v = switch (@typeInfo(@TypeOf(value))) {
                .@"struct" => |st| if (!st.is_tuple) .{value} else value,
                else => value,
            };

            var arena = std.heap.ArenaAllocator.init(gpa);
            defer arena.deinit();

            switch (signal_name) {
                inline else => |sn| {
                    if (!std.mem.eql(u8, types.guessSignature(v), types.getSignature(@field(Template, @tagName(sn).Signature)).?)) unreachable;
                    var sig = try impl.interface.connection.?.startMessage(arena.allocator());
                    defer sig.deinit();

                    sig.type = .signal;
                    sig.setInterface(Template.interface_name)
                        .setPath(impl.interface.object_path.?)
                        .setMember(@tagName(sn))
                        .setSignature(types.guessSignature(v));

                    var w = sig.writer();
                    try w.write(v);

                    try impl.interface.connection.?.sendMessage(&sig);
                    return;
                },
            }
            unreachable;
        }

        pub inline fn setProperty(impl: *@This(), comptime property: PropertiesEnum, value: @field(Template, @tagName(property)).Type) !void {
            const c = impl.interface.connection.?;

            impl.properties._mutex.lock();
            @field(impl.properties, @tagName(property)) = value;
            impl.properties._mutex.unlock();

            if (@field(Template, @tagName(property)).signal) |emit_signal| {
                switch (emit_signal) {
                    .false, .@"const" => {},
                    else => {
                        const m = try c.startMessage(null);
                        m.setInterface("org.freedesktop.DBus.Properties")
                            .setMember("PropertiesChanged")
                            .setPath(impl.interface.object_path.?)
                            .setSignature("sa{sv}as");
                        m.type = .signal;

                        defer m.deinit();
                        const ReplyDict = types.Dictionary(types.String, PropertiesUnion);

                        const w = m.writer();
                        try w.write(types.String{ .value = interface_name });

                        if (emit_signal == .true) {
                            var membuf: [1024]u8 = undefined;
                            var fixalloc = std.heap.FixedBufferAllocator.init(&membuf);
                            var d = ReplyDict.init(fixalloc.allocator());
                            try d.put(@tagName(property), @unionInit(PropertiesUnion, @tagName(property), value));
                            try w.write(d);
                        } else {
                            const invalidated: []const types.String = &.{types.String{ .value = @tagName(property) }};
                            try w.write(invalidated);
                        }

                        try c.sendMessage(&m);
                    },
                }
            }
        }

        pub fn getProperty(impl: *@This(), comptime property: PropertiesEnum) @field(Template, @tagName(property)).Type {
            impl.properties._mutex.lock();
            defer impl.properties._mutex.unlock();
            return @field(impl.properties, @tagName(property));
        }

        fn method_call(iface: *Interface, message: *Message, allocator: mem.Allocator) Error!?Message {
            const impl: *@This() = @fieldParentPtr("interface", iface);
            inline for (methods) |method_name| {
                if (!mem.eql(u8, method_name, message.fields.member.?)) comptime continue;

                const Method = @field(Template, method_name);

                var reader = message.reader() catch return error.HandlingFailed;
                const args = reader.read(Method.Arguments, allocator) catch return error.HandlingFailed;
                const params = .{&impl.data} ++ args;

                const rt_info = @typeInfo(Method.ReturnType);
                const rval = ret: switch (rt_info) {
                    .error_union => |eu| {
                        const result = @call(.auto, Method.@"fn", params);
                        const res_data: eu.payload = result catch |err| {
                            var error_return = iface.connection.?.startMessage(allocator) catch return error.HandlingFailed;
                            error_return.type = .@"error";
                            error_return.fields = .{
                                .destination = message.fields.sender,
                                .reply_serial = message.serial,
                                .error_name = std.fmt.allocPrint(allocator, "{s}.Error.{s}", .{ iface.name, @errorName(err) }) catch return error.HandlingFailed,
                            };
                            return error_return;
                        };
                        break :ret res_data;
                    },
                    else => @call(.auto, Method.@"fn", params),
                };

                if (message.flags.no_reply_expected) return null;
                var response = iface.connection.?.startMessage(allocator) catch return error.HandlingFailed;
                response.type = .method_response;
                response.fields = .{
                    .destination = message.fields.sender,
                    .reply_serial = message.serial,
                    .signature = types.getSignature(rval),
                };
                const w = response.writer();
                w.write(rval) catch return error.HandlingFailed;
                return response;
            }

            var unhandled = iface.connection.?.startMessage(allocator) catch return error.HandlingFailed;
            unhandled.type = .@"error";
            unhandled.fields = .{
                .destination = message.fields.sender,
                .reply_serial = message.serial,
                .error_name = "org.freedesktop.DBus.Error.UnknownMethod",
            };
            return unhandled;
        }

        fn property_op(iface: *Interface, io: std.Io, message: *Message, allocator: mem.Allocator) Error!?Message {
            const impl: *@This() = @fieldParentPtr("interface", iface);

            const Op = enum(u32) {
                GetAll,
                Get,
                Set,
                NoOp,
            };

            const op: Op =
                if (mem.eql(u8, message.fields.member.?, "GetAll")) .GetAll else if (mem.eql(u8, message.fields.member.?, "Get")) .Get else if (mem.eql(u8, message.fields.member.?, "Set")) .Set else .NoOp;

            var reply = iface.connection.?.startMessage(allocator) catch return error.HandlingFailed;
            reply.type = .method_response;
            reply.fields = .{ .destination = message.fields.sender, .reply_serial = message.serial };

            switch (op) {
                .GetAll => {
                    impl.properties._mutex.lockUncancelable(io);
                    defer impl.properties._mutex.unlock(io);
                    const ReplyDict = types.Dictionary(types.String, PropertiesUnion);

                    var values = ReplyDict.init(allocator);
                    inline for (properties) |property_name| {
                        if (@field(Template, property_name).mode == .Write) comptime continue;
                        values.put(.{ .value = property_name }, @unionInit(PropertiesUnion, property_name, @field(impl.properties, property_name))) catch return error.HandlingFailed;
                    }

                    const w = reply.writer();
                    w.write(values) catch return error.HandlingFailed;
                    return reply;
                },
                .Get, .Set => {
                    const r = message.reader() catch unreachable;
                    const req = r.read(types.String, allocator) catch return error.HandlingFailed;
                    inline for (properties) |property_name| {
                        if (!mem.eql(u8, req.value, property_name)) comptime continue;
                        const mode = @field(Template, property_name).mode;
                        if (op == .Set) {
                            if (mode == .Read) {
                                reply.type = .@"error";
                                reply.fields.error_name = allocator.dupe(u8, "org.freedesktop.DBus.Properties.PropertyReadOnly") catch return error.HandlingFailed;
                                reply.fields.signature = "s";
                                const w = reply.writer();
                                w.write(types.String{
                                    .value = std.fmt.comptimePrint("Property named {s} is a read-only property.", .{property_name}),
                                }) catch return error.HandlingFailed;
                                return reply;
                            }
                            const value = (r.read(union(enum) {
                                v: @FieldType(PropertiesType, property_name),
                            }, allocator) catch return error.HandlingFailed).v;
                            @field(impl.properties, property_name) = value;
                            return reply;
                        } else {
                            if (mode == .Write) {
                                reply.type = .@"error";
                                reply.fields.error_name = allocator.dupe(u8, "org.freedesktop.DBus.Properties.PropertyWriteOnly") catch return error.HandlingFailed;
                                reply.fields.signature = "s";
                                const w = reply.writer();
                                w.write(types.String{
                                    .value = std.fmt.comptimePrint("Property named {s} is a write-only property.", .{property_name}),
                                }) catch return error.HandlingFailed;
                                return reply;
                            }

                            const w = reply.writer();
                            const ValueUnion = union(enum) {
                                v: @FieldType(PropertiesType, property_name),
                            };
                            w.write(ValueUnion{ .v = @field(impl.properties, property_name) }) catch return error.HandlingFailed;
                            reply.fields.signature = "v";
                            return reply;
                        }
                    }
                    var unhandled = iface.connection.?.startMessage(allocator) catch return error.HandlingFailed;
                    unhandled.type = .@"error";
                    unhandled.fields = .{
                        .destination = message.fields.sender,
                        .reply_serial = message.serial,
                        .error_name = "org.freedesktop.DBus.Error.UnknownProperty",
                    };
                    return unhandled;
                },
                else => {
                    var unhandled = iface.connection.?.startMessage(allocator) catch return error.HandlingFailed;
                    unhandled.type = .@"error";
                    unhandled.fields = .{
                        .destination = message.fields.sender,
                        .reply_serial = message.serial,
                        .error_name = "org.freedesktop.DBus.Error.UnknownMethod",
                    };
                    return unhandled;
                },
            }
            unreachable;
        }

        /// Allocate new Implementation of interface using passed allocator. Implementation's .properties is initialized
        /// to `undefined`, so it's caller's responsibility to properly initialize .properties field.
        pub fn create(allocator: mem.Allocator) error{OutOfMemory}!*@This() {
            const impl = try allocator.create(@This());
            impl.* = @This(){};

            // We pass interface pointer to init, so downstream implementation gets some pointer of known type.
            // This is useful for some cases that piss me off (like for example org.freedesktop.DBus.Properties,
            // that requires or hardcoding implementation into library, or some way to get connection's state)
            if (std.meta.hasMethod(Template, "init")) try impl.data.init(&impl.interface, allocator);

            return impl;
        }

        pub fn destroy(i: *Interface, allocator: mem.Allocator) void {
            const impl: *@This() = @fieldParentPtr("interface", i);
            // We might want to free some resources here (for example if we taken reference to interface, we release it here)
            if (std.meta.hasMethod(Template, "deinit")) impl.data.deinit(allocator);
            allocator.destroy(impl);
        }
    };

    return Impl;
}

pub fn methodCall(i: *Interface, message: *Message, allocator: mem.Allocator) Error!?Message {
    return i.vtable.method_call(i, message, allocator);
}

pub fn reference(i: *Interface) *Interface {
    _ = i.refcounter.fetchAdd(1, .seq_cst);
    return i;
}

pub fn release(i: *Interface) isize {
    return i.refcounter.fetchSub(1, .seq_cst);
}

pub fn deinit(i: *Interface, allocator: mem.Allocator) void {
    i.vtable.destroy(i, allocator);
}

pub fn bind(i: *Interface, c: *Connection, path: []const u8) void {
    i.connection = c;
    i.object_path = path;
}

const std = @import("std");
const mem = std.mem;
const atomic = std.atomic;
const BuiltinType = std.builtin.Type;

const Connection = @import("../Connection.zig");
const Message = @import("Message.zig");
const types = @import("dbus_types.zig");
const methodList = types.methodList;
const propertyList = types.propertyList;
const signalList = types.signalList;
const PropertyStorage = types.PropertiesStorage;
